build:
	docker build -t ubuntu .
run : 
	docker run -d -it --name ubuntu -p 8000:8000 -v /Users/lune/Documents/GitHub/docker/ubuntu:/app ubuntu
exec :
	docker exec -it ubuntu /bin/bash
ps :
	docker ps -a
img :
	docker images
