version: "3.7"

services:
  db:
    image: mongodb 
    ports:
      - 27017:27017
    volumes:
      - ./db/mongod.conf:/etc/mongod.conf
#    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
