version: "3.7"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .:/app
      - ./data:/data/db
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
